export const folderIconMap = {
  src: 'vscode-icons:folder-type-src-opened',
  view: 'vscode-icons:folder-type-view-opened',
  views: 'vscode-icons:folder-type-view-opened',
  util: 'catppuccin:folder-utils-open',
  utils: 'catppuccin:folder-utils-open',
  store: 'emojione-v1:department-store',
  stores: 'emojione-v1:department-store',
  public: 'vscode-icons:folder-type-public-opened',
  publics: 'vscode-icons:folder-type-public-opened',
  config: 'vscode-icons:folder-type-config-opened',
  configs: 'vscode-icons:folder-type-config-opened',
  test: 'vscode-icons:folder-type-test-opened',
  tests: 'vscode-icons:folder-type-test-opened',

  dist: 'vscode-icons:folder-type-dist-opened',
  build: 'vscode-icons:folder-type-dist-opened',
  out: 'vscode-icons:folder-type-dist-opened',

  docs: 'catppuccin:folder-docs-open',
  locales: 'vscode-icons:folder-type-locale-opened',
  locale: 'vscode-icons:folder-type-locale-opened',
  image: 'vscode-icons:folder-type-images-opened',
  images: 'vscode-icons:folder-type-images-opened',
  api: 'vscode-icons:folder-type-api-opened',
  serves: 'vscode-icons:folder-type-api-opened',
  serve: 'vscode-icons:folder-type-api-opened',
  asset: 'vscode-icons:folder-type-asset-opened',
  assets: 'vscode-icons:folder-type-asset-opened',
  style: 'vscode-icons:folder-type-style-opened',
  styles: 'vscode-icons:folder-type-style-opened',
  mock: 'vscode-icons:folder-type-mock-opened',
  mocks: 'vscode-icons:folder-type-mock-opened',
  router: 'vscode-icons:folder-type-route-opened',
  route: 'vscode-icons:folder-type-route-opened',
  routers: 'vscode-icons:folder-type-route-opened',
  routes: 'vscode-icons:folder-type-route-opened',
  component: 'vscode-icons:folder-type-component-opened',
  components: 'vscode-icons:folder-type-component-opened',
  constant: 'catppuccin:folder-constant-open',
  constants: 'catppuccin:folder-constant-open',
  module: 'vscode-icons:folder-type-module-opened',
  modules: 'vscode-icons:folder-type-module-opened'
}
