export const folderIconMap = {
  src: 'vscode-icons:folder-type-src-opened',
  view: 'vscode-icons:folder-type-view-opened',
  views: 'vscode-icons:folder-type-view-opened',
  util: 'catppuccin:folder-utils-open',
  utils: 'catppuccin:folder-utils-open',
  store: 'fa-solid:store-alt',
  stores: 'fa-solid:store-alt',
  public: 'vscode-icons:folder-type-public-opened',
  publics: 'vscode-icons:folder-type-public-opened',
  config: 'catppuccin:folder-config-open',
  configs: 'catppuccin:folder-config-open',
  test: 'vscode-icons:folder-type-test-opened',
  tests: 'vscode-icons:folder-type-test-opened',
  dist: 'catppuccin:folder-dist-open',
  build: 'catppuccin:folder-dist-open',
  out: 'catppuccin:folder-dist-open',
  docs: 'catppuccin:folder-docs-open',
  locales: 'catppuccin:folder-locales-open',
  locale: 'catppuccin:folder-locales-open'
}
